unique_ids:
  assets:
    standard-page.html: TPYRW2BMML36Y2OFU4PIMEDBNB4REFSZ
    theme.css: UM5SVW756RX53C5EA4WFY5NWWVB52Y6M
  forms:
    Form1: 47BO2I2JK7DMFVDKNVVN3XXXTSZB5ACQ
  modules: {}
  scripts: {}
  server_modules: {}
